<a href="https://colab.research.google.com/github/snovamo86861/MachineLearning/blob/master/Torch/Clase_2_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

import pandas as pd


#Trabajando con Tensores

In [9]:
torch.version

<module 'torch.version' from '/usr/local/lib/python3.6/dist-packages/torch/version.py'>

In [11]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [15]:
tensor_b = torch.Tensor(2, 2) #2, 2 dimension con valores aleatoros se una Tensor con mayuscula) #Tensor con T masyuscula en una mezcla entre el metodo de tensor en minuscula y vacio
tensor_b

tensor([[2.9364e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])

In [16]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[2.9368e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])


tensor([[0.4064, 0.6283],
        [0.7194, 0.9784]])

In [17]:
# tensor con valores aleatoreos

tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.5271, 0.7467],
        [0.7839, 0.4395]])

In [18]:
result = tensor_b + tensor_c
result

tensor([[0.9335, 1.3750],
        [1.5033, 1.4179]])

In [19]:
#Shape
result.shape

torch.Size([2, 2])

In [21]:
result.shape
reshape = result.view(4,1)
reshape

tensor([[0.9335],
        [1.3750],
        [1.5033],
        [1.4179]])

In [25]:
#otro tensor , que no es aleatoreo
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)
points[0][1] = 2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [27]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [29]:
p_t = points.t()
p_t, p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [31]:
# Este tensor sirve para imagenes

tensor_x = torch.tensor([1, 2, 3, 4])
#tensor_x, torch.unsqueeze(tensor_x, 0)
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))